### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by chuxiaoyi2018** [WenjieWWJ/DecRS#1]
您好
最近看了你们的发表在KDD2021的《Deconfounded Recommendation for Alleviating Bias Amplification》关于因果推理去偏的研究
感觉写的非常好，并且也有开源代码
最近我们想将你们的方案在我们的业务上进行尝试
但是在复现的时候发现你们生成confounder_prior.npy等等都是直接使用现成的npy文件
所以可以问一下你们的数据预处理，也就是生成npy这一部分的代码可以方便公布在github上面吗

不胜感激~

**Comment by WenjieWWJ** [comment]
很抱歉之前没注意到issue。
那个是统计的每个category在数据集里面的分布情况，可以很方便地统计自己所用数据集的category的分布。甚至可以自己控制每个category的理想先验分布，有些工作也会利用均匀分布来作为先验。
希望这些信息有所帮助，谢谢提问。
